//+------------------------------------------------------------------+
//|                                                TestRule_EMA.mq5  |
//|                                      Generated by Hermes Agent   |
//+------------------------------------------------------------------+
#property copyright "Hermes"
#property link      ""
#property version   "1.00"

enum ENUM_TEST_RULE
  {
   RULE_EMA=0,   // EMA Crossover
   RULE_RSI=1,   // RSI OB/OS
   RULE_MACD=2,  // MACD Zero Cross
   RULE_COMBINED=3 // Combined Rule (To be updated later)
  };

input ENUM_TEST_RULE InpActiveRule = RULE_EMA;
input int FastEMA = 10;
input int SlowEMA = 20;
input int InpRSIPeriod = 14;
input int InpMACDFast = 12;
input int InpMACDSlow = 26;
input int InpMACDSignal = 9;
input double RiskPercent = 1.0;
input double ATRMultiplier = 2.0;

int handleFast, handleSlow, handleRSI, handleMACD, handleATR;
double fastArr[], slowArr[], rsiArr[], macdMainArr[], macdSignalArr[], atrArr[];
int csvHandle = INVALID_HANDLE;
int magicNumber = 12345;

#include <Trade\Trade.mqh>
CTrade trade;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   handleFast = iMA(_Symbol, _Period, FastEMA, 0, MODE_EMA, PRICE_CLOSE);
   handleSlow = iMA(_Symbol, _Period, SlowEMA, 0, MODE_EMA, PRICE_CLOSE);
   handleRSI = iRSI(_Symbol, _Period, InpRSIPeriod, PRICE_CLOSE);
   handleMACD = iMACD(_Symbol, _Period, InpMACDFast, InpMACDSlow, InpMACDSignal, PRICE_CLOSE);
   handleATR = iATR(_Symbol, _Period, 14);
   
   if(handleFast == INVALID_HANDLE || handleSlow == INVALID_HANDLE || handleRSI == INVALID_HANDLE || handleMACD == INVALID_HANDLE || handleATR == INVALID_HANDLE)
      return(INIT_FAILED);
      
   ArraySetAsSeries(fastArr, true);
   ArraySetAsSeries(slowArr, true);
   ArraySetAsSeries(rsiArr, true);
   ArraySetAsSeries(macdMainArr, true);
   ArraySetAsSeries(macdSignalArr, true);
   ArraySetAsSeries(atrArr, true);
   
   trade.SetExpertMagicNumber(magicNumber);
   
   csvHandle = FileOpen("validation_trades.csv", FILE_WRITE|FILE_READ|FILE_CSV|FILE_COMMON|FILE_ANSI, ",");
   if(csvHandle != INVALID_HANDLE)
     {
      FileSeek(csvHandle, 0, SEEK_END);
      if(FileSize(csvHandle) == 0)
         FileWrite(csvHandle, "Time", "Rule", "Type", "Price", "SL", "TP", "Lot");
     }
   
   return(INIT_SUCCEEDED);
  }

void OnDeinit(const int reason)
  {
   if(csvHandle != INVALID_HANDLE)
      FileClose(csvHandle);
  }

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   if(PositionsTotal() > 0) return; // Wait for flat position
   
   CopyBuffer(handleFast, 0, 0, 3, fastArr);
   CopyBuffer(handleSlow, 0, 0, 3, slowArr);
   CopyBuffer(handleRSI, 0, 0, 3, rsiArr);
   CopyBuffer(handleMACD, 0, 0, 3, macdMainArr);
   CopyBuffer(handleMACD, 1, 0, 3, macdSignalArr); // 1 = Signal Line
   CopyBuffer(handleATR, 0, 0, 1, atrArr);
   
   double atr = atrArr[0];
   if(atr <= 0) return;
   
   double slDist = atr * ATRMultiplier;
   double tpDist = slDist; // 1:1 RR Constraint
   
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   
   // Calculate Lot Size based on 1% Risk
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double riskAmount = balance * (RiskPercent / 100.0);
   double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   if(tickSize == 0 || tickValue == 0) return;
   
   double slPoints = slDist / tickSize;
   double lot = riskAmount / (slPoints * tickValue);
   
   // Normalize Lot
   double minLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double maxLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   double lotStep = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   lot = MathMax(minLot, MathMin(maxLot, MathFloor(lot / lotStep) * lotStep));
   
   bool buySignal = false;
   bool sellSignal = false;
   string ruleName = "";
   
   if(InpActiveRule == RULE_EMA)
     {
      ruleName = "EMA_Cross";
      if(fastArr[1] > slowArr[1] && fastArr[2] <= slowArr[2]) buySignal = true;
      if(fastArr[1] < slowArr[1] && fastArr[2] >= slowArr[2]) sellSignal = true;
     }
   else if(InpActiveRule == RULE_RSI)
     {
      ruleName = "RSI_OB_OS";
      if(rsiArr[1] > 30 && rsiArr[2] <= 30) buySignal = true;
      if(rsiArr[1] < 70 && rsiArr[2] >= 70) sellSignal = true;
     }
   else if(InpActiveRule == RULE_MACD)
     {
      ruleName = "MACD_Zero_Cross";
      if(macdMainArr[1] > 0 && macdMainArr[2] <= 0) buySignal = true;
      if(macdMainArr[1] < 0 && macdMainArr[2] >= 0) sellSignal = true;
     }
   else if(InpActiveRule == RULE_COMBINED)
     {
      ruleName = "Combined_Rule";
      // To be filled dynamically later based on analysis
     }
     
   if(buySignal)
     {
      double sl = ask - slDist;
      double tp = ask + tpDist;
      if(trade.Buy(lot, _Symbol, ask, sl, tp, "Validation Buy"))
        {
         if(csvHandle != INVALID_HANDLE)
           {
            FileWrite(csvHandle, TimeToString(TimeCurrent()), ruleName, "BUY", ask, sl, tp, lot);
            FileFlush(csvHandle);
           }
        }
     }
   else if(sellSignal)
     {
      double sl = bid + slDist;
      double tp = bid - tpDist;
      if(trade.Sell(lot, _Symbol, bid, sl, tp, "Validation Sell"))
        {
         if(csvHandle != INVALID_HANDLE)
           {
            FileWrite(csvHandle, TimeToString(TimeCurrent()), ruleName, "SELL", bid, sl, tp, lot);
            FileFlush(csvHandle);
           }
        }
     }
  }
