//+------------------------------------------------------------------+
//|                                              Universal_EA.mq5    |
//|                                      Generated by Hermes Agent   |
//+------------------------------------------------------------------+
#property copyright "Hermes"
#property link      ""
#property version   "1.00"

input int InpActiveRule = 0;
input double RiskPercent = 1.0;
input double ATRMultiplier = 2.0;

int hMA1, hMA2, hRSI, hBB, hStoch, hMACD, handleATR;
double ma1Arr[], ma2Arr[], rsiArr[], bbUpper[], bbLower[], bbMid[], stochMain[], stochSig[], macdMain[], macdSig[], atrArr[];
int csvHandle = INVALID_HANDLE;
int magicNumber = 8888;

#include <Trade\Trade.mqh>
CTrade trade;

int OnInit()
  {
   hMA1 = iMA(_Symbol, _Period, 10, 0, MODE_EMA, PRICE_CLOSE);
   hMA2 = iMA(_Symbol, _Period, 20, 0, MODE_EMA, PRICE_CLOSE);
   hRSI = iRSI(_Symbol, _Period, 14, PRICE_CLOSE);
   hBB = iBands(_Symbol, _Period, 20, 0, 2.0, PRICE_CLOSE);
   hMACD = iMACD(_Symbol, _Period, 12, 26, 9, PRICE_CLOSE);
   handleATR = iATR(_Symbol, _Period, 14);
   
   if(hMA1 == INVALID_HANDLE || hMA2 == INVALID_HANDLE || hRSI == INVALID_HANDLE || hBB == INVALID_HANDLE || hMACD == INVALID_HANDLE || handleATR == INVALID_HANDLE)
      return(INIT_FAILED);
      
   ArraySetAsSeries(ma1Arr, true);
   ArraySetAsSeries(ma2Arr, true);
   ArraySetAsSeries(rsiArr, true);
   ArraySetAsSeries(bbUpper, true);
   ArraySetAsSeries(bbLower, true);
   ArraySetAsSeries(bbMid, true);
   ArraySetAsSeries(macdMain, true);
   ArraySetAsSeries(macdSig, true);
   ArraySetAsSeries(atrArr, true);
   
   trade.SetExpertMagicNumber(magicNumber);
   
   csvHandle = FileOpen("validation_trades.csv", FILE_WRITE|FILE_READ|FILE_CSV|FILE_COMMON|FILE_ANSI, ",");
   if(csvHandle != INVALID_HANDLE)
     {
      FileSeek(csvHandle, 0, SEEK_END);
      if(FileSize(csvHandle) == 0)
         FileWrite(csvHandle, "Time", "Rule", "Type", "Price", "SL", "TP", "Lot");
     }
   
   return(INIT_SUCCEEDED);
  }

void OnDeinit(const int reason)
  {
   if(csvHandle != INVALID_HANDLE)
      FileClose(csvHandle);
  }

void GetSignal_Trend_MA(bool &b, bool &s) {
   if(ma1Arr[1] > ma2Arr[1] && ma1Arr[2] <= ma2Arr[2]) b = true;
   if(ma1Arr[1] < ma2Arr[1] && ma1Arr[2] >= ma2Arr[2]) s = true;
}

void GetSignal_Momentum_RSI(bool &b, bool &s) {
   if(rsiArr[1] > 30 && rsiArr[2] <= 30) b = true;
   if(rsiArr[1] < 70 && rsiArr[2] >= 70) s = true;
}

void GetSignal_Volatility_BB(bool &b, bool &s) {
   double close = iClose(_Symbol, _Period, 1);
   if(close < bbLower[1]) b = true;
   if(close > bbUpper[1]) s = true;
}

void GetSignal_Breakout_Price(bool &b, bool &s) {
   // Simple Highest High breakout
   double h1 = iHigh(_Symbol, _Period, 1);
   double h2 = iHigh(_Symbol, _Period, 2);
   double h3 = iHigh(_Symbol, _Period, 3);
   if(h1 > h2 && h1 > h3) b = true;
   
   double l1 = iLow(_Symbol, _Period, 1);
   double l2 = iLow(_Symbol, _Period, 2);
   double l3 = iLow(_Symbol, _Period, 3);
   if(l1 < l2 && l1 < l3) s = true;
}

void GetSignal_Oscillator_MACD(bool &b, bool &s) {
   if(macdMain[1] > 0 && macdMain[2] <= 0) b = true;
   if(macdMain[1] < 0 && macdMain[2] >= 0) s = true;
}

void OnTick()
  {
   if(PositionsTotal() > 0) return; 
   
   CopyBuffer(hMA1, 0, 0, 3, ma1Arr);
   CopyBuffer(hMA2, 0, 0, 3, ma2Arr);
   CopyBuffer(hRSI, 0, 0, 3, rsiArr);
   CopyBuffer(hBB, 1, 0, 3, bbUpper);
   CopyBuffer(hBB, 2, 0, 3, bbLower);
   CopyBuffer(hBB, 0, 0, 3, bbMid);
   CopyBuffer(hMACD, 0, 0, 3, macdMain);
   CopyBuffer(hMACD, 1, 0, 3, macdSig);
   CopyBuffer(handleATR, 0, 0, 1, atrArr);
   
   double atr = atrArr[0];
   if(atr <= 0) return;
   
   double slDist = atr * ATRMultiplier;
   double tpDist = slDist; // 1:1 RR Constraint
   
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double riskAmount = balance * (RiskPercent / 100.0);
   double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   if(tickSize == 0 || tickValue == 0) return;
   
   double slPoints = slDist / tickSize;
   double lot = riskAmount / (slPoints * tickValue);
   
   double minLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double maxLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   double lotStep = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   lot = MathMax(minLot, MathMin(maxLot, MathFloor(lot / lotStep) * lotStep));
   
   bool buySignal = false;
   bool sellSignal = false;
   string ruleName = "";
   
   if(InpActiveRule == 0) { ruleName = "Trend_MA"; GetSignal_Trend_MA(buySignal, sellSignal); }
   else if(InpActiveRule == 1) { ruleName = "Momentum_RSI"; GetSignal_Momentum_RSI(buySignal, sellSignal); }
   else if(InpActiveRule == 2) { ruleName = "Volatility_BB"; GetSignal_Volatility_BB(buySignal, sellSignal); }
   else if(InpActiveRule == 3) { ruleName = "Breakout_Price"; GetSignal_Breakout_Price(buySignal, sellSignal); }
   else if(InpActiveRule == 4) { ruleName = "Oscillator_MACD"; GetSignal_Oscillator_MACD(buySignal, sellSignal); }
   else if(InpActiveRule == 99) {
      // [DYNAMIC_COMBINED_LOGIC_HERE]
   }
     
   if(buySignal)
     {
      double sl = ask - slDist;
      double tp = ask + tpDist;
      if(trade.Buy(lot, _Symbol, ask, sl, tp, "Validation Buy"))
        {
         if(csvHandle != INVALID_HANDLE)
           {
            FileWrite(csvHandle, TimeToString(TimeCurrent()), ruleName, "BUY", ask, sl, tp, lot);
            FileFlush(csvHandle);
           }
        }
     }
   else if(sellSignal)
     {
      double sl = bid + slDist;
      double tp = bid - tpDist;
      if(trade.Sell(lot, _Symbol, bid, sl, tp, "Validation Sell"))
        {
         if(csvHandle != INVALID_HANDLE)
           {
            FileWrite(csvHandle, TimeToString(TimeCurrent()), ruleName, "SELL", bid, sl, tp, lot);
            FileFlush(csvHandle);
           }
        }
     }
  }
