import os
import glob
import re
from pathlib import Path

source_dir = r"G:\My Drive\jobot\EA Week1"
output_dir = r"G:\My Drive\save log-blueprint-skill\EA-Knowledge-Base\raw\EA_Week1_Analysis"

os.makedirs(output_dir, exist_ok=True)

files = glob.glob(os.path.join(source_dir, "*.mq*"))

def analyze_ea(file_path):
    name = os.path.basename(file_path)
    with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
        content = f.read()
        
    lower_content = content.lower()
    
    is_fxdreema = 'fxdreema' in lower_content or 'blockcalls' in lower_content
    
    categories = []
    if 'grid' in lower_content or 'hedg' in lower_content or 'zone recovery' in lower_content:
        categories.append('Grid/Hedging')
    if 'martingale' in lower_content or 'multiply' in lower_content or 'recovery' in lower_content:
        categories.append('Martingale')
    if 'rsi' in lower_content or 'macd' in lower_content or 'ema' in lower_content or 'bolinger' in lower_content or 'bb' in lower_content or 'indicator' in lower_content:
        categories.append('Indicator/Price Action')
    if '1326' in lower_content or "d'alembert" in lower_content or 'flip coin' in lower_content:
        categories.append('Casino Betting Systems')
        
    if not categories:
        categories.append('General/Unknown')
        
    inputs = re.findall(r'^(?:input|extern)\s+[^;]+;', content, re.MULTILINE)
    # limit to 20 inputs to keep report concise
    inputs_str = "\n".join(inputs[:20])
    if len(inputs) > 20:
        inputs_str += f"\n... (and {len(inputs)-20} more)"
        
    pros_cons = ""
    for cat in categories:
        if 'Martingale' in cat:
            pros_cons += "- **Martingale**\n  - 🟢 Pros: Extremely high short-term win rate, simple logic.\n  - 🔴 Cons: High risk of ruin (margin call) in strong trending markets without pullbacks.\n"
        elif 'Grid/Hedging' in cat:
            pros_cons += "- **Grid/Hedging**\n  - 🟢 Pros: Excellent cash flow in sideways/ranging markets. Hedging buys time.\n  - 🔴 Cons: Heavy margin tie-up. Highly vulnerable to strong breakouts.\n"
        elif 'Indicator' in cat:
            pros_cons += "- **Indicator/Price Action**\n  - 🟢 Pros: Clear logical entries, easy to backtest and limit risk per trade.\n  - 🔴 Cons: Indicators are lagging. High rate of false signals in choppy markets.\n"
        elif 'Casino' in cat:
            pros_cons += "- **Casino Betting Systems**\n  - 🟢 Pros: Fast portfolio growth during winning streaks.\n  - 🔴 Cons: Ignores market context (trends/volatility).\n"
            
    md_content = f"""---
title: "{name} Analysis"
tags: ["ea-analysis", "week1", "mql"]
---

# EA Analysis: {name}

## 1. Overview
- **File:** `{name}`
- **Source:** EA Week1
- **Architecture:** {'fxDreema Generated (Block-based)' if is_fxdreema else 'Native MQL Handwritten'}
- **Identified Categories:** {', '.join(categories)}

## 2. Pros & Cons Evaluation
{pros_cons}

## 3. Key Input Parameters
```mql4
{inputs_str if inputs_str else "// No standard input parameters found"}
```

## 4. Conclusion
This EA heavily relies on the {categories[0]} strategy. {'Because it was generated by fxDreema, the core logic is abstracted. The input parameters above indicate the configurable variables exposed to the user.' if is_fxdreema else 'The native code structure allows for direct modification.'} 
"""

    out_name = f"{name}_analysis.md".replace(" ", "_").replace("(", "").replace(")", "").replace("+", "Plus")
    with open(os.path.join(output_dir, out_name), 'w', encoding='utf-8') as out:
        out.write(md_content)

for idx, f in enumerate(files):
    analyze_ea(f)

print(f"Generated {len(files)} markdown reports in {output_dir}")
